# -*- mode: python ; coding: utf-8 -*-
import os
import subprocess

# --- Auto-generate _version.py before build ---
version = os.environ.get("RELEASE_VERSION")

if not version:
    try:
        version = subprocess.check_output(
            ["git", "describe", "--tags", "--always"],
            stderr=subprocess.DEVNULL
        ).decode("utf-8").strip()
    except Exception:
        version = "0.0.0-dev"

# Clean up leading 'v' prefix (e.g., v1.0.0 -> 1.0.0)
version = version.lstrip("v")

# Write the version module into your source directory
version_file_path = os.path.join('src', 'rift_fitness_tracker', '_version.py')
with open(version_file_path, 'w') as f:
    f.write(f'# Auto-generated by PyInstaller spec file\nVERSION = "{version}"\n')

# --- PyInstaller Analysis ---
a = Analysis(
    ['src/rift_fitness_tracker/main.py'],
    pathex=['src'],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='RiftFitnessTracker',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)